// Generated automatically by nearley
// http://github.com/Hardmath123/nearley
(function () {
function id(x) {return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "entity$subexpression$1", "symbols": [/[bB]/, /[aA]/, /[tT]/, /[sS]/, /[mM]/, /[aA]/, /[nN]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "entity", "symbols": ["entity$subexpression$1"]},
    {"name": "entity$subexpression$2", "symbols": [/[bB]/, /[aA]/, /[tT]/, /[sS]/, /[mM]/, /[eE]/, /[nN]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "entity", "symbols": ["entity$subexpression$2"]},
    {"name": "entity$subexpression$3", "symbols": [/[bB]/, /[oO]/, /[wW]/, /[lL]/, /[eE]/, /[rR]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "entity", "symbols": ["entity$subexpression$3"]},
    {"name": "entity$subexpression$4", "symbols": [/[bB]/, /[oO]/, /[wW]/, /[lL]/, /[eE]/, /[rR]/, /[sS]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "entity", "symbols": ["entity$subexpression$4"]},
    {"name": "entity$subexpression$5", "symbols": [/[cC]/, /[rR]/, /[iI]/, /[cC]/, /[kK]/, /[eE]/, /[tT]/, /[eE]/, /[rR]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "entity", "symbols": ["entity$subexpression$5"]},
    {"name": "entity$subexpression$6", "symbols": [/[cC]/, /[rR]/, /[iI]/, /[cC]/, /[kK]/, /[eE]/, /[tT]/, /[eE]/, /[rR]/, /[sS]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "entity", "symbols": ["entity$subexpression$6"]},
    {"name": "entity$subexpression$7", "symbols": [/[uU]/, /[mM]/, /[pP]/, /[iI]/, /[rR]/, /[eE]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "entity", "symbols": ["entity$subexpression$7"]},
    {"name": "entity$subexpression$8", "symbols": [/[uU]/, /[mM]/, /[pP]/, /[iI]/, /[rR]/, /[eE]/, /[sS]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "entity", "symbols": ["entity$subexpression$8"]},
    {"name": "entity$subexpression$9", "symbols": [/[fF]/, /[iI]/, /[eE]/, /[lL]/, /[dD]/, /[eE]/, /[rR]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "entity", "symbols": ["entity$subexpression$9"]},
    {"name": "entity$subexpression$10", "symbols": [/[fF]/, /[iI]/, /[eE]/, /[lL]/, /[dD]/, /[eE]/, /[rR]/, /[sS]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "entity", "symbols": ["entity$subexpression$10"]},
    {"name": "format$subexpression$1", "symbols": [/[oO]/, /[dD]/, /[iI]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "format", "symbols": ["format$subexpression$1"]},
    {"name": "format$subexpression$2", "symbols": [/[tT]/, /[eE]/, /[sS]/, /[tT]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "format", "symbols": ["format$subexpression$2"]},
    {"name": "format$subexpression$3", "symbols": [/[tT]/, {"literal":"2"}, {"literal":"0"}], "postprocess": function (d) {return d.join(""); }},
    {"name": "format", "symbols": ["format$subexpression$3"]},
    {"name": "format$subexpression$4", "symbols": [/[aA]/, /[lL]/, /[lL]/, {"literal":" "}, /[fF]/, /[oO]/, /[rR]/, /[mM]/, /[aA]/, /[tT]/, /[sS]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "format", "symbols": ["format$subexpression$4"]},
    {"name": "tournaments$subexpression$1", "symbols": [/[aA]/, /[sS]/, /[iI]/, /[aA]/, {"literal":" "}, /[cC]/, /[uU]/, /[pP]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "tournaments", "symbols": ["tournaments$subexpression$1"]},
    {"name": "tournaments$subexpression$2", "symbols": [/[wW]/, /[oO]/, /[rR]/, /[lL]/, /[dD]/, {"literal":" "}, /[cC]/, /[uU]/, /[pP]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "tournaments", "symbols": ["tournaments$subexpression$2"]},
    {"name": "tournaments$subexpression$3", "symbols": [/[iI]/, /[pP]/, /[lL]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "tournaments", "symbols": ["tournaments$subexpression$3"]},
    {"name": "tournaments$subexpression$4", "symbols": [/[pP]/, /[sS]/, /[lL]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "tournaments", "symbols": ["tournaments$subexpression$4"]},
    {"name": "ws", "symbols": [{"literal":" "}]},
    {"name": "ws", "symbols": [{"literal":" "}, "ws"]},
    {"name": "wicketpos", "symbols": ["numpos", "aftern"]},
    {"name": "wicketpos", "symbols": ["numpos", "ws", "aftern"]},
    {"name": "wicketpos", "symbols": ["alphapos"]},
    {"name": "numpos", "symbols": [/[1-9]/]},
    {"name": "numpos$string$1", "symbols": [{"literal":"1"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "numpos", "symbols": ["numpos$string$1"]},
    {"name": "aftern$string$1", "symbols": [{"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aftern", "symbols": ["aftern$string$1"]},
    {"name": "aftern$string$2", "symbols": [{"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aftern", "symbols": ["aftern$string$2"]},
    {"name": "aftern$string$3", "symbols": [{"literal":"r"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aftern", "symbols": ["aftern$string$3"]},
    {"name": "aftern$string$4", "symbols": [{"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aftern", "symbols": ["aftern$string$4"]},
    {"name": "alphapos$string$1", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"r"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "alphapos", "symbols": ["alphapos$string$1"]},
    {"name": "alphapos$string$2", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "alphapos", "symbols": ["alphapos$string$2"]},
    {"name": "alphapos$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"r"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "alphapos", "symbols": ["alphapos$string$3"]},
    {"name": "alphapos$string$4", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "alphapos", "symbols": ["alphapos$string$4"]},
    {"name": "alphapos$string$5", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "alphapos", "symbols": ["alphapos$string$5"]},
    {"name": "alphapos$string$6", "symbols": [{"literal":"s"}, {"literal":"i"}, {"literal":"x"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "alphapos", "symbols": ["alphapos$string$6"]},
    {"name": "alphapos$string$7", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "alphapos", "symbols": ["alphapos$string$7"]},
    {"name": "alphapos$string$8", "symbols": [{"literal":"e"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "alphapos", "symbols": ["alphapos$string$8"]},
    {"name": "alphapos$string$9", "symbols": [{"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "alphapos", "symbols": ["alphapos$string$9"]},
    {"name": "alphapos$string$10", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "alphapos", "symbols": ["alphapos$string$10"]},
    {"name": "alphapos$string$11", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "alphapos", "symbols": ["alphapos$string$11"]},
    {"name": "achievement$string$1", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"a"}, {"literal":"k"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "achievement", "symbols": ["achievement$string$1"]},
    {"name": "achievement$string$2", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":" "}, {"literal":"g"}, {"literal":"e"}, {"literal":"t"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "achievement", "symbols": ["achievement$string$2"]},
    {"name": "achievement$string$3", "symbols": [{"literal":"s"}, {"literal":"c"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "achievement", "symbols": ["achievement$string$3"]},
    {"name": "achievement$string$4", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "achievement", "symbols": ["achievement$string$4"]},
    {"name": "achievement$string$5", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "achievement", "symbols": ["achievement$string$5"]},
    {"name": "achievement$string$6", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "achievement", "symbols": ["achievement$string$6"]},
    {"name": "achievement$string$7", "symbols": [{"literal":"c"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "achievement", "symbols": ["achievement$string$7"]},
    {"name": "achievement$string$8", "symbols": [{"literal":"s"}, {"literal":"c"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "achievement", "symbols": ["achievement$string$8"]},
    {"name": "achievement", "symbols": ["partnership"]},
    {"name": "partnership$string$1", "symbols": [{"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}, {"literal":"h"}, {"literal":"i"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "partnership", "symbols": ["partnership$string$1"]},
    {"name": "partnership$string$2", "symbols": [{"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}, {"literal":"h"}, {"literal":"i"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "partnership", "symbols": ["nthwicket", "ws", "partnership$string$2"]},
    {"name": "nthwicket$string$1", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "nthwicket", "symbols": ["wicketpos", "ws", "nthwicket$string$1"]},
    {"name": "skill$subexpression$1", "symbols": [/[bB]/, /[aA]/, /[tT]/, /[tT]/, /[iI]/, /[nN]/, /[gG]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "skill", "symbols": ["skill$subexpression$1"]},
    {"name": "skill$subexpression$2", "symbols": [/[bB]/, /[oO]/, /[wW]/, /[lL]/, /[iI]/, /[nN]/, /[gG]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "skill", "symbols": ["skill$subexpression$2"]},
    {"name": "skill$subexpression$3", "symbols": [/[fF]/, /[iI]/, /[eE]/, /[lL]/, /[dD]/, /[iI]/, /[nN]/, /[gG]/], "postprocess": function (d) {return d.join(""); }},
    {"name": "skill", "symbols": ["skill$subexpression$3"]},
    {"name": "environsel", "symbols": ["entityenviron"]},
    {"name": "environsel", "symbols": ["statsenviron"]},
    {"name": "environsel", "symbols": ["achievementenviron"]},
    {"name": "entityenviron", "symbols": ["entity", "ws", "environ"]},
    {"name": "statsenviron", "symbols": ["stats", "ws", "environ"]},
    {"name": "achievementenviron", "symbols": ["achievement", "ws", "environ"]},
    {"name": "stats$string$1", "symbols": [{"literal":"a"}, {"literal":"v"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "stats", "symbols": ["skill", "ws", "stats$string$1"]},
    {"name": "environ$string$1", "symbols": [{"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "environ", "symbols": ["environ$string$1", "ws", "arena"]},
    {"name": "arena", "symbols": ["format"]},
    {"name": "arena", "symbols": ["tournaments"]},
    {"name": "minimax", "symbols": ["maxima"]},
    {"name": "minimax", "symbols": ["minima"]},
    {"name": "maxima$string$1", "symbols": [{"literal":"b"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "maxima", "symbols": ["maxima$string$1"]},
    {"name": "maxima$string$2", "symbols": [{"literal":"t"}, {"literal":"o"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "maxima", "symbols": ["maxima$string$2"]},
    {"name": "maxima$string$3", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "maxima", "symbols": ["maxima$string$3"]},
    {"name": "maxima$string$4", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "maxima", "symbols": ["maxima$string$4"]},
    {"name": "maxima$string$5", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "maxima", "symbols": ["maxima$string$5"]},
    {"name": "minima$string$1", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "minima", "symbols": ["minima$string$1"]},
    {"name": "minima$string$2", "symbols": [{"literal":"l"}, {"literal":"e"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "minima", "symbols": ["minima$string$2"]},
    {"name": "minima$string$3", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"w"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "minima", "symbols": ["minima$string$3"]},
    {"name": "minima$string$4", "symbols": [{"literal":"s"}, {"literal":"l"}, {"literal":"o"}, {"literal":"w"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "minima", "symbols": ["minima$string$4"]},
    {"name": "cricnlp", "symbols": ["minimax", "ws", "environsel"]}
]
  , ParserStart: "cricnlp"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
